esphome:
  name: safephrase-wake
  comment: "ESP32 INMP441 wake-word detector for SafePhrase system"
  platformio_options:
    board_build.flash_mode: dio
    # build_flags:
    #   # Disable app_trace completely
    #   - -DCONFIG_APPTRACE_ENABLE=0
    #   - -DCONFIG_APPTRACE_DEST_NONE=1
    #   - -DCONFIG_APPTRACE_ONPANIC_ENABLE=0
    #   - -DCONFIG_APPTRACE_POSTMORTEM_ENABLE=0
    #   - -DCONFIG_APPTRACE_GCOV_ENABLE=0
    #   - -DCONFIG_APPTRACE_SV_ENABLE=0
    #   - -DCONFIG_APPTRACE_USE_FLASH_MEM=0
    #   - -DCONFIG_APPTRACE_MEMBUFS_APPTRACE_PROTO_ENABLE=0

    #   # Disable FreeRTOS trace (optional)
    #   - -DCONFIG_FREERTOS_USE_TRACE_FACILITY=0
    #   - -DCONFIG_FREERTOS_ENABLE_TASK_SNAPSHOT=0

    # build_unflags:
    #   - -Werror=all
    #   - -DCONFIG_APPTRACE_ENABLE=1
    #   - -DCONFIG_APPTRACE_DEST_TRAX=1
    #   - -DCONFIG_APPTRACE_DEST_UART=1

  on_boot:
    priority: -10
    then:
      - logger.log: "Wake word detection starting..."

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_ADF_SUPPORT: y        # enable esp_adf
      CONFIG_ESP_SR_WN9_ENABLE: y      # enable WakeNet9
      CONFIG_ESP_SR_MN1_ENABLE: n
      CONFIG_ESP_SR_MN2_ENABLE: n

logger:
  level: INFO

api:

ota:
  platform: esphome

  
wifi:
  power_save_mode: none
  ap:
    ssid: "safephrase-wake"
    password: "SafePhrase1234"

# ----------------------------
# INMP441 Microphone (I²S)
# ----------------------------
i2s_audio:
  - id: mic_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO26

microphone:
  - platform: i2s_audio
    id: inmp441_mic
    adc_type: external
    i2s_audio_id: mic_bus
    i2s_din_pin: GPIO22
    channel: left

# ----------------------------
# Voice Assistant / Wake Word
# ----------------------------
voice_assistant:
  microphone: inmp441_mic
  noise_suppression_level: 2
  use_wake_word: true
  on_wake_word_detected:
    - logger.log: "Wake word detected!"
    - output.turn_on: pi_trigger
    - delay: 0.5s
    - output.turn_off: pi_trigger

# ----------------------------
# GPIO output to Raspberry Pi
# ----------------------------
output:
  - platform: gpio
    id: pi_trigger
    pin: GPIO4

# ----------------------------
# Optional LED indicator
# ----------------------------
light:
  - platform: binary
    name: "Wake LED"
    output: pi_trigger
