esphome:
  name: safephrase-wake
  comment: "ESP32 INMP441 wake-word detector for SafePhrase system"
  platformio_options:
    board_build.flash_mode: dio
    build_flags:
      - -DCONFIG_SPIRAM_CACHE_WORKAROUND=1   # Stability fix for audio
      

  on_boot:
    priority: -10
    then:
      - logger.log: "============================"
      - logger.log: "SafePhrase Wake System Boot"
      - logger.log: "============================"
      - delay: 10s
      - logger.log: "Wake word detection starting..."
      - logger.log: "Mic initialization complete. Waiting for voice activity..."

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_ADF_SUPPORT: y        # enable esp_adf
      CONFIG_ESP_SR_WN9_ENABLE: y      # enable WakeNet9
      CONFIG_ESP_SR_MN1_ENABLE: n
      CONFIG_ESP_SR_MN2_ENABLE: n
      # CONFIG_LOG_DEFAULT_LEVEL_VERBOSE: y
      # CONFIG_ESP_CONSOLE_UART_DEFAULT: y
      # CONFIG_ESP_CONSOLE_UART_TX_GPIO: "1"
      # CONFIG_ESP_CONSOLE_UART_RX_GPIO: "3"

logger:
  level: VERY_VERBOSE
  hardware_uart: UART0   # Ensures logs show on serial console

api:

ota:
  platform: esphome

wifi:
  ssid: "TECNO SPARK 5 Air"
  password: "1234567890"
  power_save_mode: none
  ap:
    ssid: "safephrase-wake"
    password: "SafePhrase1234"

# ----------------------------
# INMP441 Microphone (I²S)
# ----------------------------
i2s_audio:
  - id: mic_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO26

microphone:
  - platform: i2s_audio
    id: inmp441_mic
    adc_type: external
    i2s_audio_id: mic_bus
    i2s_din_pin: GPIO22
    channel: left

# ----------------------------
# Voice Assistant / Wake Word
# ----------------------------
voice_assistant:
  microphone: inmp441_mic
  noise_suppression_level: 2
  use_wake_word: true
  on_wake_word_detected:
    - logger.log: "Wake word detected!"
    - output.turn_on: pi_trigger
    - delay: 0.5s
    - output.turn_off: pi_trigger
  on_listening:
    - logger.log: "Listening for wake word..."
  on_error:
    - logger.log: "⚠️ Voice assistant encountered an error."

# ----------------------------
# GPIO output to Raspberry Pi
# ----------------------------
output:
  - platform: gpio
    id: pi_trigger
    pin: GPIO4

# ----------------------------
# Optional LED indicator
# ----------------------------
light:
  - platform: binary
    name: "Wake LED"
    output: pi_trigger
